### ISSUE TITLE
Save as lfactor and load dataset with lfactor

### ISSUE THREAD

**Issue by patseraos** [pdbailey0/lfactors#2]
Hi,

I found your extremely useful package `lfactors`, which I used to create a dataset  in R.  I used the `lfactor` function to assign labels and levels to categorical variables and save the file in a SPSS format, since some collaborators use SPSS, and to a R format. I've tried to save using `saveRDS` and `save`. However, when I load the dataset, the variables are no longer `lfactor` but `factor`. So, I'm unable to select values based on levels and labels. Is there any way to save lfactor and read lfactors in a data.table in R?  

Thank you for your help!

**Comment by pdbailey0** [comment]
Hi @patseraos, thanks for the kind comments and question. If I may, do you have reproducable code that shows this? Specifically, was the `lfactors` package loaded when you ran `readRDS`?

**Comment by patseraos** [comment]
Hi @pdbailey0 

Thank you for your quick reply. I can't believe this was something was easy. I didn't think of trying to import the package before loading the dataset, but if it works. Thank you! 

However, I came across another when trying to create a reproducible example:

    mtcars$new <- sample(c(1:3), size=dim(mtcars)[1], replace = T)
    mtcars$new2 <- sample(c(1,2,99), size=dim(mtcars)[1], replace = T)
    str(mtcars)

    library(lfactors)
    mtcars$new <- lfactor(mtcars$new, levels = 1:3, labels = c("A", "B", "C"))
    mtcars$new2 <- lfactor(mtcars$new, levels = c(1,2,99), labels = c("D", "E", "F"))
    str(mtcars)

There seem to be an issue when converting the variable `new2` to lfactor. Although I haven't come across this issue before, I'm saving the final dataset to RDS and SAV (some collaborators use SPSS) and in SPSS the levels get changed to 1,2,3 in the case of variables similar to new2. I'm not sure is this is an issue with SPSS though.

**Comment by pdbailey0** [comment]
@patseraos you've got a bug in your code. You want to use `new2` in the call to `lfactors` on the penultimate line of code.

**Comment by pdbailey0** [comment]
Resolved: import `lfactors` before reloading it from an RDS.
